# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: Azure_Kinect_ROS_Driver-$(SourceBranchName)-$(Date:yyyyMMdd)-$(Rev:rrr)

trigger:
  batch: true
  branches:
    include:
    - master
    - develop
    - melodic

pr:
  autoCancel: true
  branches:
    include: 
    - master
    - develop
    - melodic

jobs:
- job: WindowsNoetic
  displayName: Windows Noetic

  pool:
    vmImage: 'windows-2019'

  steps:
  - checkout: self
    clean: "all"
    fetchDepth: 20
    lfs: false
    persistCredentials: true
    submodules: true
    path: colcon_ws\src\Azure_Kinect_ROS_Driver

  # Download and install the Azure Kinect Sensor SDK 
  - powershell: |
      wget http://download.microsoft.com/download/1/9/8/198048e8-63f2-45c6-8f96-1fd541d1b4bc/Azure%20Kinect%20SDK%201.2.0.msi -OutFile $(Build.SourcesDirectory)\sdk.msi
      $(Build.SourcesDirectory)\sdk.msi /passive

  - script: |
      conda env create -f colcon_ws\src\Azure_Kinect_ROS_Driver\environment.yml
      conda activate colcon
      mkdir colcon_ws\src\deps
      vcs import colcon_ws\src\deps < colcon_ws\src\Azure_Kinect_ROS_Driver\deps.rosinstall
      set COLCON_HOME=colcon_ws\src\Azure_Kinect_ROS_Driver\
      colcon build
    displayName: Create Catkin Workspace

- job: LinuxMelodic
  displayName: Linux Melodic

  pool:
    vmImage: 'ubuntu-16.04'

  container: 
    image: ros:melodic-perception-bionic
    options: "--name ci-container -v /usr/bin/docker:/tmp/docker:ro"

  steps:
  - script: |
      /tmp/docker exec -t -u 0 ci-container \
      sh -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -y install sudo"
    displayName: Enable sudo

  - checkout: self
    clean: "all"
    fetchDepth: 20
    lfs: false
    persistCredentials: true
    submodules: true
    path: catkin_ws/src/Azure_Kinect_ROS_Driver

  # Download and install the Azure Kinect Sensor SDK 
  - bash: |
      sudo apt-get -y install curl software-properties-common
      curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
      sudo apt-add-repository https://packages.microsoft.com/ubuntu/18.04/prod
      sudo apt-get update
      echo libk4a1.2 libk4a1.2/accept-eula boolean true | sudo debconf-set-selections
      echo libk4a1.2 libk4a1.2/accepted-eula-hash string 0f5d5c5de396e4fee4c0753a21fee0c1ed726cf0316204edda484f08cb266d76 | sudo debconf-set-selections -u
      sudo apt-get -y install libk4a1.2-dev
    displayName: Install the Azure Kinect Sensor SDK

  # Build the catkin workspace
  - bash: |
      source /opt/ros/melodic/setup.bash
      catkin_make --force-cmake
    displayName: Build ROS Driver Node
    workingDirectory: ../../
